spring.application.name=backend

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=none

# GLPI-Konfiguration: eigene (nicht Spring-Standard-) Properties,
# die wir gleich in einer eigenen Config-Klasse einlesen
glpi.api-url=${GLPI_API_URL}
glpi.app-token=${GLPI_APP_TOKEN}
glpi.user-token=${GLPI_USER_TOKEN}
